apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: audit-reader-binding
  namespace: default
subjects:
- kind: User
  name: security
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: audit-reader
  apiGroup: rbac.authorization.k8s.io