apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: integration-read-only-binding
  namespace: default
subjects:
- kind: User
  name: infra
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: integration-read-only
  apiGroup: rbac.authorization.k8s.io