apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smart-home-gateway-editor-binding
  namespace: default
subjects:
- kind: User
  name: smarthome
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: smart-home-gateway-editor
  apiGroup: rbac.authorization.k8s.io